---
ansible_connection: httpapi
ansible_network_os: eos
ansible_user: admin
ansible_ssh_pass: admin
ansible_become: yes
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false

ansible_python_interpreter: /usr/bin/python3

local_git_repo_path: "/Users/mthiel/git_projects/homelabs"
