---

- name: Validate Reachability
  connection: httpapi
  hosts: NODES
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

    - name: Test reachability between all devices
      eos_command:
        commands:
          - "ping vrf MGMT 8.8.8.8"
          - "ping vrf MGMT 1.1.1.1"
      register: ping_result

    - name: Create Report
      template:
        src: ../templates/ping_report.j2
        dest: reports/ping_report.md
