###############################################################
# Device Inventory:
# Add new section for each device you want to manage configlets
# Required fields:
#  Key:
#    name:
#    configlets:
#    parentContainerName:
#
# Note: You do no need to list configlets that are inherited
#       from a container the device is attached to.  CVP will
#       merge them together
###############################################################

devices_inventory:
  VEOS1:
    name: VEOS1
    parentContainerName: vEOS
    configlets:
      - DC1_VEOS1-BASE
  SW1:
    name: SW1
    parentContainerName: TESTING
    configlets:
      - DC1_SW1-BASE
